### ISSUE TITLE
Part Not available

### ISSUE THREAD

**Issue by KevinRiTE** [cyborg5/qtpyhat#1]
The TSMP58000 is no longer available. Is the TSMP98000 a direct replacement?

**Comment by cyborg5** [comment]
I'm so sorry it took me so long to get back to you on this. I took a quick look at the specs and it is recommended replacement but I didn't want to say anything until right actually tested it myself. I obtained the newer chip and verified it does work okay on a breadboard. I can't say I've soldered one into a qtpyhat yet but it should work just fine. I will update the docs on the Adafruit learning system and
